name: hirfi_home
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
# B
  blurrycontainer: ^2.1.0
# C
  cupertino_icons: ^1.0.8
  connectivity_plus: ^6.1.3
  cloud_firestore: ^5.6.5
  calendar_date_picker2: ^2.0.0
# F
  firebase_storage: ^12.4.4
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  firebase_messaging: ^15.2.4
  firebase_database: ^11.3.4
  flutter_localization: ^0.3.1
  flutter_svg: ^2.0.17
#G
  get_storage: ^2.1.1
  get: ^4.7.2
  geocoding: ^3.0.0

  geolocator: ^14.0.0
  google_maps_flutter: ^2.12.2
  google_api_headers: ^4.4.3

  geolocator: ^9.0.2
  google_maps_flutter: ^2.11.0
  # google_api_headers: ^4.4.3


#H
  http: ^1.3.0
#I
  intl: ^0.19.0
  image_picker: ^1.1.2
#J
  json_annotation: ^4.9.0
#L
  location: ^8.0.0
#M
  multi_select_flutter: ^4.1.3
#O
  outline_gradient_button: ^2.0.1+1
#P
  permission_handler: ^12.0.0+1
#R
  responsive_framework: ^1.5.1
#S
  smooth_page_indicator: ^1.2.1
  shared_preferences: ^2.5.2
  supabase_flutter: ^2.8.4
#T
  toasty_box: ^1.0.4
  text_gradiate: ^1.0.1
  pin_code_fields: ^8.0.1

  dropdown_search: ^6.0.2
  dropdown_model_list: ^2.1.5
  dropdown_button2: ^2.3.9
  
=======
  dropdown_button2: ^2.3.9

  
  
  
  
  
  
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/png/
    - assets/images/icon/
    - assets/images/jpg/onbording/
    - assets/images/png/logo/

  fonts:
    - family: inter
      fonts:
        - asset: assets/fonts/inter/Inter_18pt-Regular.ttf
        - asset: assets/fonts/inter/Inter_18pt-SemiBold.ttf
        - asset: assets/fonts/inter/Inter_18pt-Bold.ttf

  
    - family: tajawal
      fonts:
        - asset: assets/fonts/tajawal/Tajawal-Regular.ttf
        - asset: assets/fonts/tajawal/Tajawal-Medium.ttf
        - asset: assets/fonts/tajawal/Tajawal-Bold.ttf


