// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeftwHLaZuH9NlOHvp0wuWbyAFdMMSEMg',
    appId: '1:831594090007:web:892dce5aa92cdac4581652',
    messagingSenderId: '831594090007',
    projectId: 'hirfi-home',
    authDomain: 'hirfi-home.firebaseapp.com',
    storageBucket: 'hirfi-home.firebasestorage.app',
    measurementId: 'G-3L4441N486',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNoHQdk1kV2dTtPRc_So3Jd3x-oM_BKLU',
    appId: '1:831594090007:android:542aed87cf1249f6581652',
    messagingSenderId: '831594090007',
    projectId: 'hirfi-home',
    storageBucket: 'hirfi-home.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXWT07nLwA-3goKJGQfnkdxSyUEebwnmo',
    appId: '1:831594090007:ios:ff907125507dbc6b581652',
    messagingSenderId: '831594090007',
    projectId: 'hirfi-home',
    storageBucket: 'hirfi-home.firebasestorage.app',
    iosBundleId: 'com.example.hirfiHome',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXWT07nLwA-3goKJGQfnkdxSyUEebwnmo',
    appId: '1:831594090007:ios:ff907125507dbc6b581652',
    messagingSenderId: '831594090007',
    projectId: 'hirfi-home',
    storageBucket: 'hirfi-home.firebasestorage.app',
    iosBundleId: 'com.example.hirfiHome',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCeftwHLaZuH9NlOHvp0wuWbyAFdMMSEMg',
    appId: '1:831594090007:web:ed628d7c60ff6692581652',
    messagingSenderId: '831594090007',
    projectId: 'hirfi-home',
    authDomain: 'hirfi-home.firebaseapp.com',
    storageBucket: 'hirfi-home.firebasestorage.app',
    measurementId: 'G-02EQDMYQYT',
  );
}
